# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 李智渊的个人博客
email: 605248452@qq.com
description: > # this means to ignore newlines until "baseurl:"
  每天进步一点点
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://a605248452.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  a605248452

# Build settings
markdown: kramdown
